@baseUrl = http://localhost:3000
@contentType = application/json

@adminToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxNTVkYTE1MC0zOWQyLTRmMmItYTlkYi1kY2YxMWY2ZjZkMWUiLCJlbWFpbCI6Im1hcmtuZHdpZ2FAZ21haWwuY29tIiwicm9sZSI6IkFETUlOIiwiaWF0IjoxNzUwMTExMTY1LCJleHAiOjE3NTAxOTc1NjV9.wnIB55t02rS05LAyDgnv-cEuu-CGa0cMDygLp2qoUDQ
@adminId = 155da150-39d2-4f2b-a9db-dcf11f6f6d1e

@userToken = 
@userId =  

@projectId =  

### Create a new project
POST {{baseUrl}}/projects
Authorization: Bearer {{adminToken}}
Content-Type: {{contentType}}

{
    "name": "New Project",
    "description": "Easy Project",
    "endDate": "2025-06-30T23:59:59Z"
}



### Get all projects
GET {{baseUrl}}/projects
Authorization: Bearer {{adminToken}}

### Get project by ID
GET {{baseUrl}}/projects/{{projectId}}
Authorization: Bearer {{adminToken}}

### Assign project to user
PUT {{baseUrl}}/projects/{{projectId}}
Authorization: Bearer {{adminToken}}
Content-Type: {{contentType}}

{
    "assigneeId": "{{userId}}"
}

### Mark project as completed
PATCH {{baseUrl}}/projects/{{projectId}}/complete
Authorization: Bearer {{userToken}}
Content-Type: {{contentType}}

### Delete project
DELETE {{baseUrl}}/projects/{{projectId}}
Authorization: Bearer {{adminToken}}
